# coding: utf-8

"""
    Voyager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v6.0.0
    Contact: hello@appscode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import client
from client.rest import ApiException
from client.models.v1beta1_ingress_tls import V1beta1IngressTLS


class TestV1beta1IngressTLS(unittest.TestCase):
    """ V1beta1IngressTLS unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1IngressTLS(self):
        """
        Test V1beta1IngressTLS
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = client.models.v1beta1_ingress_tls.V1beta1IngressTLS()
        pass


if __name__ == '__main__':
    unittest.main()
