# coding: utf-8

"""
    Voyager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v6.0.0
    Contact: hello@appscode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import client
from client.rest import ApiException
from client.apis.voyager_appscode_com_api import VoyagerAppscodeComApi


class TestVoyagerAppscodeComApi(unittest.TestCase):
    """ VoyagerAppscodeComApi unit test stubs """

    def setUp(self):
        self.api = client.apis.voyager_appscode_com_api.VoyagerAppscodeComApi()

    def tearDown(self):
        pass

    def test_get_api_group(self):
        """
        Test case for get_api_group

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
