# coding: utf-8

"""
    Voyager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v6.0.0
    Contact: hello@appscode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import client
from client.rest import ApiException
from client.apis.voyager_appscode_com_v1beta1_api import VoyagerAppscodeComV1beta1Api


class TestVoyagerAppscodeComV1beta1Api(unittest.TestCase):
    """ VoyagerAppscodeComV1beta1Api unit test stubs """

    def setUp(self):
        self.api = client.apis.voyager_appscode_com_v1beta1_api.VoyagerAppscodeComV1beta1Api()

    def tearDown(self):
        pass

    def test_create_namespaced_certificate(self):
        """
        Test case for create_namespaced_certificate

        
        """
        pass

    def test_create_namespaced_ingress(self):
        """
        Test case for create_namespaced_ingress

        
        """
        pass

    def test_delete_collection_namespaced_certificate(self):
        """
        Test case for delete_collection_namespaced_certificate

        
        """
        pass

    def test_delete_collection_namespaced_ingress(self):
        """
        Test case for delete_collection_namespaced_ingress

        
        """
        pass

    def test_delete_namespaced_certificate(self):
        """
        Test case for delete_namespaced_certificate

        
        """
        pass

    def test_delete_namespaced_ingress(self):
        """
        Test case for delete_namespaced_ingress

        
        """
        pass

    def test_get_api_resources(self):
        """
        Test case for get_api_resources

        
        """
        pass

    def test_list_certificate_for_all_namespaces(self):
        """
        Test case for list_certificate_for_all_namespaces

        
        """
        pass

    def test_list_ingress_for_all_namespaces(self):
        """
        Test case for list_ingress_for_all_namespaces

        
        """
        pass

    def test_list_namespaced_certificate(self):
        """
        Test case for list_namespaced_certificate

        
        """
        pass

    def test_list_namespaced_ingress(self):
        """
        Test case for list_namespaced_ingress

        
        """
        pass

    def test_patch_namespaced_certificate(self):
        """
        Test case for patch_namespaced_certificate

        
        """
        pass

    def test_patch_namespaced_ingress(self):
        """
        Test case for patch_namespaced_ingress

        
        """
        pass

    def test_read_namespaced_certificate(self):
        """
        Test case for read_namespaced_certificate

        
        """
        pass

    def test_read_namespaced_ingress(self):
        """
        Test case for read_namespaced_ingress

        
        """
        pass

    def test_replace_namespaced_certificate(self):
        """
        Test case for replace_namespaced_certificate

        
        """
        pass

    def test_replace_namespaced_ingress(self):
        """
        Test case for replace_namespaced_ingress

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
