# coding: utf-8

"""
    Voyager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v6.0.0
    Contact: hello@appscode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import client
from client.rest import ApiException
from client.models.io_k8s_api_core_v1_load_balancer_ingress import IoK8sApiCoreV1LoadBalancerIngress


class TestIoK8sApiCoreV1LoadBalancerIngress(unittest.TestCase):
    """ IoK8sApiCoreV1LoadBalancerIngress unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1LoadBalancerIngress(self):
        """
        Test IoK8sApiCoreV1LoadBalancerIngress
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = client.models.io_k8s_api_core_v1_load_balancer_ingress.IoK8sApiCoreV1LoadBalancerIngress()
        pass


if __name__ == '__main__':
    unittest.main()
