# coding: utf-8

"""
    Voyager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v6.0.0
    Contact: hello@appscode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import client
from client.rest import ApiException
from client.models.io_k8s_apimachinery_pkg_apis_meta_v1_watch_event import IoK8sApimachineryPkgApisMetaV1WatchEvent


class TestIoK8sApimachineryPkgApisMetaV1WatchEvent(unittest.TestCase):
    """ IoK8sApimachineryPkgApisMetaV1WatchEvent unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApisMetaV1WatchEvent(self):
        """
        Test IoK8sApimachineryPkgApisMetaV1WatchEvent
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = client.models.io_k8s_apimachinery_pkg_apis_meta_v1_watch_event.IoK8sApimachineryPkgApisMetaV1WatchEvent()
        pass


if __name__ == '__main__':
    unittest.main()
