# coding: utf-8

"""
    Voyager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v6.0.0
    Contact: hello@appscode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import client
from client.rest import ApiException
from client.models.v1beta1_http_ingress_path import V1beta1HTTPIngressPath


class TestV1beta1HTTPIngressPath(unittest.TestCase):
    """ V1beta1HTTPIngressPath unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1HTTPIngressPath(self):
        """
        Test V1beta1HTTPIngressPath
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = client.models.v1beta1_http_ingress_path.V1beta1HTTPIngressPath()
        pass


if __name__ == '__main__':
    unittest.main()
