# coding: utf-8

"""
    Voyager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v6.0.0
    Contact: hello@appscode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class V1beta1AuthOption(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'basic': 'V1beta1BasicAuth',
        'tls': 'V1beta1TLSAuth'
    }

    attribute_map = {
        'basic': 'basic',
        'tls': 'tls'
    }

    def __init__(self, basic=None, tls=None):
        """
        V1beta1AuthOption - a model defined in Swagger
        """

        self._basic = None
        self._tls = None
        self.discriminator = None

        if basic is not None:
          self.basic = basic
        if tls is not None:
          self.tls = tls

    @property
    def basic(self):
        """
        Gets the basic of this V1beta1AuthOption.

        :return: The basic of this V1beta1AuthOption.
        :rtype: V1beta1BasicAuth
        """
        return self._basic

    @basic.setter
    def basic(self, basic):
        """
        Sets the basic of this V1beta1AuthOption.

        :param basic: The basic of this V1beta1AuthOption.
        :type: V1beta1BasicAuth
        """

        self._basic = basic

    @property
    def tls(self):
        """
        Gets the tls of this V1beta1AuthOption.

        :return: The tls of this V1beta1AuthOption.
        :rtype: V1beta1TLSAuth
        """
        return self._tls

    @tls.setter
    def tls(self, tls):
        """
        Sets the tls of this V1beta1AuthOption.

        :param tls: The tls of this V1beta1AuthOption.
        :type: V1beta1TLSAuth
        """

        self._tls = tls

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, V1beta1AuthOption):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
