# coding: utf-8

"""
    Voyager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v6.0.0
    Contact: hello@appscode.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class V1beta1BasicAuth(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'realm': 'str',
        'secret_name': 'str'
    }

    attribute_map = {
        'realm': 'realm',
        'secret_name': 'secretName'
    }

    def __init__(self, realm=None, secret_name=None):
        """
        V1beta1BasicAuth - a model defined in Swagger
        """

        self._realm = None
        self._secret_name = None
        self.discriminator = None

        if realm is not None:
          self.realm = realm
        if secret_name is not None:
          self.secret_name = secret_name

    @property
    def realm(self):
        """
        Gets the realm of this V1beta1BasicAuth.

        :return: The realm of this V1beta1BasicAuth.
        :rtype: str
        """
        return self._realm

    @realm.setter
    def realm(self, realm):
        """
        Sets the realm of this V1beta1BasicAuth.

        :param realm: The realm of this V1beta1BasicAuth.
        :type: str
        """

        self._realm = realm

    @property
    def secret_name(self):
        """
        Gets the secret_name of this V1beta1BasicAuth.

        :return: The secret_name of this V1beta1BasicAuth.
        :rtype: str
        """
        return self._secret_name

    @secret_name.setter
    def secret_name(self, secret_name):
        """
        Sets the secret_name of this V1beta1BasicAuth.

        :param secret_name: The secret_name of this V1beta1BasicAuth.
        :type: str
        """

        self._secret_name = secret_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, V1beta1BasicAuth):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
